In [1]:
import pandas as pd
from sklearn import preprocessing

In [3]:
Kerala_floods = pd.read_csv('C:/Users/rajes/Downloads/archive/warnings_actual_predicted.csv')

In [4]:
Kerala_floods

district        date actual_rainfall predicted_rainfall
0    Alappuzha  08-10-2018           Green             Yellow
1    Alappuzha  08-11-2018           Green                Red
2    Alappuzha  08-12-2018           Green                Red
3    Alappuzha   8/13/2018           Green             Orange
4    Alappuzha   8/14/2018           Green             Orange
..         ...         ...             ...                ...
205    Wayanad   8/20/2018           Green              Green
206    Wayanad   8/21/2018           Green              Green
207    Wayanad   8/22/2018           Green              Green
208    Wayanad  08-08-2018             Red             Orange
209    Wayanad  08-09-2018             Red             Yellow

[210 rows x 4 columns]

In [5]:
Kerala_floods.actual_rainfall = Kerala_floods.actual_rainfall.astype('category')
Kerala_floods.actual_rainfall = Kerala_floods.actual_rainfall.cat.reorder_categories(['Green','Yellow','Orange','Red'])
Kerala_floods.actual_rainfall = Kerala_floods.actual_rainfall.cat.codes

Kerala_floods.predicted_rainfall = Kerala_floods.predicted_rainfall.astype('category')
Kerala_floods.predicted_rainfall = Kerala_floods.predicted_rainfall.cat.reorder_categories(['Green','Yellow','Orange','Red'])
Kerala_floods.predicted_rainfall = Kerala_floods.predicted_rainfall.cat.codes

In [6]:
Kerala_floods

district        date  actual_rainfall  predicted_rainfall
0    Alappuzha  08-10-2018                0                   1
1    Alappuzha  08-11-2018                0                   3
2    Alappuzha  08-12-2018                0                   3
3    Alappuzha   8/13/2018                0                   2
4    Alappuzha   8/14/2018                0                   2
..         ...         ...              ...                 ...
205    Wayanad   8/20/2018                0                   0
206    Wayanad   8/21/2018                0                   0
207    Wayanad   8/22/2018                0                   0
208    Wayanad  08-08-2018                3                   2
209    Wayanad  08-09-2018                3                   1

[210 rows x 4 columns]

In [7]:
X = Kerala_floods.iloc[:,2].values
X = X.reshape(-1,1)
X

array([[0],
       [0],
       [0],
       [0],
       [0],
       [3],
       [3],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [3],
       [3],
       [2],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [3],
       [1],
       [0],
       [2],
       [2],
       [3],
       [3],
       [3],
       [3],
       [2],
       [0],
       [0],
       [0],
       [3],
       [3],
       [0],
       [0],
       [0],
       [1],
       [1],
       [3],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [2],
       [2],
       [0],
       [0],
       [0],
       [1],
       [2],
       [3],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [3],
       [1],
       [1],
    

In [8]:
y = Kerala_floods.iloc[:,3].values
y

array([1, 3, 3, 2, 2, 2, 2, 2, 1, 1, 0, 0, 0, 2, 1, 1, 3, 3, 2, 2, 2, 3,
       3, 3, 1, 0, 0, 0, 2, 1, 3, 3, 3, 3, 3, 3, 3, 3, 3, 1, 0, 0, 0, 2,
       1, 3, 3, 3, 2, 1, 3, 3, 3, 1, 0, 0, 0, 0, 2, 1, 1, 1, 2, 1, 1, 3,
       2, 1, 0, 0, 0, 0, 0, 2, 1, 1, 1, 1, 0, 0, 1, 2, 2, 1, 0, 0, 0, 0,
       1, 0, 1, 1, 1, 1, 1, 1, 2, 2, 1, 1, 0, 0, 0, 2, 1, 3, 3, 3, 2, 1,
       1, 3, 3, 1, 1, 0, 0, 0, 2, 1, 2, 3, 3, 2, 1, 1, 3, 3, 1, 1, 0, 0,
       0, 2, 1, 3, 3, 3, 2, 1, 1, 3, 3, 1, 1, 0, 0, 0, 2, 1, 1, 2, 1, 2,
       1, 1, 2, 3, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 2, 1, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 2, 3, 1, 1, 0, 0, 0, 2, 1, 3, 3, 3,
       3, 3, 3, 3, 3, 1, 1, 0, 0, 0, 2, 1], dtype=int8)

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=0)


from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)

In [10]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
logreg = LogisticRegression(random_state=0)
logreg.fit(X_train, y_train)

LogisticRegression(random_state=0)

In [11]:
y_pred = logreg.predict(X_test)
y_pred

array([0, 3, 1, 3, 0, 1, 0, 0, 1, 1, 0, 3, 1, 0, 3, 0, 0, 3, 0, 1, 3, 0,
       1, 0, 0, 3, 3, 1, 1, 3, 1, 3, 1, 0, 3, 0, 0, 1, 0, 1, 0, 1, 3, 3,
       0, 0, 0, 3, 1, 1, 0, 0, 0], dtype=int8)

In [12]:
print('Accuracy of logistic regression classifier on train set: {:.2f}'.format(logreg.score(X_train, y_train)))

Accuracy of logistic regression classifier on train set: 0.45


In [13]:
print('Accuracy of logistic regression classifier on test set: {:.2f}'.format(logreg.score(X_test, y_test)))

Accuracy of logistic regression classifier on test set: 0.42


In [14]:
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(y_test, y_pred)
print(confusion_matrix)

[[12  0  0  0]
 [ 5  7  0  8]
 [ 2  5  0  3]
 [ 4  4  0  3]]


In [15]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.52      1.00      0.69        12
           1       0.44      0.35      0.39        20
           2       0.00      0.00      0.00        10
           3       0.21      0.27      0.24        11

    accuracy                           0.42        53
   macro avg       0.29      0.41      0.33        53
weighted avg       0.33      0.42      0.35        53



C:\Users\rajes\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\rajes\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\rajes\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
